import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

const STORAGE_KEY = 'resume-studio-data';
const uid = (prefix = 'm') => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];

const DEFAULT = {
  profile: { name: '林知行', role: '产品设计师', city: '上海 · 中国', phone: '138 0000 0000', email: 'linzhixing@email.com', website: 'linzhixing.design', photo: '' },
  modules: [
    { id: 'summary', type: 'summary', title: '个人简介', visible: false, spacing: 22, content: '拥有 5 年互联网产品设计经验，擅长从用户洞察到产品落地的全流程设计。热衷于用清晰的视觉语言解决复杂问题，曾主导多款千万级用户产品的体验升级。' },
    { id: 'experience', type: 'experience', title: '工作经历', visible: false, spacing: 22, items: [{ company: 'Arc Studio', role: '高级产品设计师', period: '2022.03 — 至今', detail: '负责核心业务线的产品体验与设计系统建设，推动跨团队协作，设计方案落地后用户转化率提升 28%。' }, { company: '有赞科技', role: '产品设计师', period: '2019.07 — 2022.02', detail: '参与商家后台和移动端产品设计，建立组件化设计规范，协助团队将研发效率提升 35%。' }] },
    { id: 'education', type: 'education', title: '教育经历', visible: true, spacing: 22, items: [{ school: '同济大学', degree: '艺术设计 · 本科', period: '2015.09 — 2019.06', city: '上海' }] },
    { id: 'skills', type: 'skills', title: '技能与工具', visible: true, spacing: 22, skills: 'Figma, Sketch, Protopie, 用户研究, 设计系统, 项目管理' },
    { id: 'projects', type: 'projects', title: '项目经历', visible: true, spacing: 22, items: [{ name: '个人作品集', role: '产品设计', period: '2023', detail: 'linzhixing.design / Dribbble: @linzhixing' }] },
    { id: 'awards', type: 'awards', title: '奖项与证书', visible: false, spacing: 22, items: [{ name: '站酷设计奖', issuer: '站酷', period: '2023', detail: '年度优秀作品' }] },
    { id: 'languages', type: 'languages', title: '语言能力', visible: false, spacing: 22, items: [{ name: '英语', level: 'CET-6 / 熟练' }, { name: '普通话', level: '母语' }] },
    { id: 'custom', type: 'custom', title: '兴趣爱好', visible: false, spacing: 22, content: '摄影、徒步、开源项目', items: [] }
  ],
  settings: { template: 'left-right', accent: '#2e2e2e', font: 'system', fontSize: 14, lineHeight: 1.65, pagePadding: 42, moduleGap: 22, columns: 'single', sectionRule: 'line', paperRadius: 0, elementStyles: { name: { fontSize: 38, x: 0, y: 0, marginBottom: 8 }, role: { fontSize: 18, x: 0, y: 0, marginBottom: 14 }, contact: { fontSize: 13, x: 0, y: 0, marginBottom: 0 }, header: { x: 0, y: 0, marginBottom: 22 } } },
  schemaVersion: 3
};
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function normalize(raw) {
  const data = raw && raw.profile ? raw : clone(DEFAULT);
  const incomingSchemaVersion = Number(data.schemaVersion || 0);
  const legacyDefault = raw && !raw.schemaVersion && data.profile.name === DEFAULT.profile.name;
  if (!data.modules) {
    data.modules = [];
    if (data.summary) data.modules.push({ id: 'summary', type: 'summary', title: '个人简介', visible: true, spacing: 22, content: data.summary });
    if (data.experience) data.modules.push({ id: 'experience', type: 'experience', title: '工作经历', visible: true, spacing: 22, items: data.experience });
    if (data.education) data.modules.push({ id: 'education', type: 'education', title: '教育经历', visible: true, spacing: 22, items: [data.education] });
    if (data.skills) data.modules.push({ id: 'skills', type: 'skills', title: '技能与工具', visible: true, spacing: 22, skills: data.skills });
    if (data.projects) data.modules.push({ id: 'projects', type: 'projects', title: '项目经历', visible: true, spacing: 22, items: [{ name: '作品集 / 项目', role: '', period: '', detail: data.projects }] });
  }
  data.settings = { ...clone(DEFAULT.settings), ...(data.settings || {}) };
  data.settings.elementStyles = { ...clone(DEFAULT.settings.elementStyles), ...(data.settings.elementStyles || {}) };
  Object.keys(DEFAULT.settings.elementStyles).forEach(key => { data.settings.elementStyles[key] = { ...clone(DEFAULT.settings.elementStyles[key]), ...(data.settings.elementStyles[key] || {}) }; });
  if (incomingSchemaVersion < 3 && data.settings.template === 'classic') { data.settings.template = 'left-right'; data.settings.accent = '#2e2e2e'; data.settings.pagePadding = 42; data.settings.paperRadius = 0; }
  if (!Number.isFinite(Number(data.settings.fontSize))) data.settings.fontSize = DEFAULT.settings.fontSize;
  if (legacyDefault) data.modules.forEach(module => { if (module.id === 'summary' || module.id === 'experience') module.visible = false; });
  data.modules = data.modules.map(module => ({ visible: true, spacing: 22, ...module, id: module.id || uid() }));
  data.schemaVersion = 3;
  return data;
}
let state = normalize(JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'));
let previewZoom = 100;
let modalSnapshot = null;
let modalTarget = null;
let selectedElement = 'name';
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function toast(message) { const node = $('#toast'); if (!node) return; node.textContent = message; node.classList.add('show'); clearTimeout(window.__toast); window.__toast = setTimeout(() => node.classList.remove('show'), 1700); }
function getModule(id) { return state.modules.find(module => module.id === id); }
function activeModules() { return state.modules.filter(module => module.visible); }
function field(label, path, value, area = false, placeholder = '') { return `<label class="control-field"><span>${label}</span>${area ? `<textarea data-path="${path}" placeholder="${placeholder}">${esc(value)}</textarea>` : `<input data-path="${path}" value="${esc(value)}" placeholder="${placeholder}">`}</label>`; }

function shell() { return `<div class="app"><main class="main"><header class="topbar"><div class="brand-lockup"><span class="brand-mark">R</span><div><strong>简历设计工作台</strong></div></div><div class="actions"><button class="btn secondary" data-action="share">↗ 分享</button><button class="btn" data-action="image">▣ 导出图片</button><button class="btn preview-top" id="top-preview" data-action="preview">⛶ 预览</button><button class="btn primary" data-action="pdf">⇩ 下载 PDF</button></div></header><div class="studio-shell"><aside class="tool-sidebar" aria-label="全局设置"><div class="tool-sidebar-label">设置</div><button class="tool-button active" data-tool="spacing" title="间距与自由布局"><span>↕</span><small>间距</small></button><button class="tool-button" data-tool="font" title="字体与字号"><span>Aa</span><small>字体</small></button><button class="tool-button" data-tool="template" title="更换模板"><span>▦</span><small>模板</small></button><div class="tool-sidebar-bottom"><button class="tool-button" data-action="pdf" title="导出"><span>⇩</span><small>导出</small></button><button class="rail-avatar" title="个人空间">林</button></div></aside><section class="resume-stage"><div class="stage-toolbar"><div><span class="eyebrow">DOCUMENT / A4</span><span class="stage-title">${esc(state.profile.name)} 的简历</span></div><div class="stage-tools"><span class="preview-state"><i></i>实时同步</span><div class="zoom"><button data-action="zoom-out" aria-label="缩小">−</button><span id="ztext">${previewZoom}%</span><button data-action="zoom-in" aria-label="放大">＋</button></div><button class="stage-preview" id="full" data-action="preview">⛶ 专注预览</button></div></div><div class="canvas"><div class="canvas-ruler ruler-top"><span>0</span><span>210 mm</span></div><div class="canvas-ruler ruler-side"><span>0</span><span>297 mm</span></div><article class="paper ${state.settings.template}" id="paper">${resume()}</article></div></section><aside class="module-sidebar" aria-label="简历模块"><div class="module-sidebar-head"><div><span class="eyebrow">RESUME STRUCTURE</span><h2>信息模块</h2></div><button class="module-add" data-action="add-module" title="添加模块">＋</button></div><div class="module-tabs"><button class="module-tab active" data-module-tab="content">信息模块</button><button class="module-tab" data-module-tab="sort">排序设置</button></div><div id="module-sidebar-content">${moduleSidebar('content')}</div></aside></div><div id="workspace-popover"></div></main></div><div id="modal-root"></div><div class="toast" id="toast"></div>`; }
function moduleSidebar(tab = 'content') { if (tab === 'sort') return `<div class="sort-intro">拖动模块卡片调整简历中的出现顺序</div><div class="module-sort-list">${state.modules.map((module, index) => `<div class="sort-row" draggable="true" data-sort-id="${module.id}"><span class="sort-grip" aria-hidden="true">⠿</span><span class="sort-index">${String(index + 1).padStart(2, '0')}</span><span class="sort-name">${esc(module.title)}</span></div>`).join('')}</div>`; return `<div class="module-list compact-module-list"><button class="module-row profile-row" data-open-profile><span class="module-row-icon">♙</span><span class="module-row-copy"><b>基本信息</b><small>姓名、职位与联系方式</small></span><span class="module-row-edit">编辑</span></button>${state.modules.map(module => `<button class="module-row ${module.visible ? '' : 'is-off'}" data-open-module="${module.id}"><span class="module-row-icon">${moduleIcon(module.type)}</span><span class="module-row-copy"><b>${esc(module.title)}</b><small>${module.visible ? '显示在简历中' : '已隐藏'}</small></span><span class="module-switch ${module.visible ? 'on' : ''}" data-module-toggle="${module.id}" role="switch" aria-checked="${module.visible}"><i></i></span></button>`).join('')}</div><button class="add-module-row" data-action="add-module"><span>＋</span>添加简历模块</button>`; }
function contentPanel() { return `<div class="profile-card"><div class="panel-intro"><div><b>基本信息</b><span>姓名和联系方式会显示在简历页首</span></div></div><div class="profile-grid">${field('姓名', 'profile.name', state.profile.name)}${field('求职职位', 'profile.role', state.profile.role)}${field('所在城市', 'profile.city', state.profile.city)}${field('联系电话', 'profile.phone', state.profile.phone)}${field('电子邮箱', 'profile.email', state.profile.email)}${field('个人网站', 'profile.website', state.profile.website)}</div></div><div class="panel-intro"><div><b>简历模块</b><span>关闭、删除、排序和调节模块间距，导出时会保持你的设置</span></div><button class="btn small" data-action="add-module">＋ 添加模块</button></div><div class="module-list">${state.modules.map((module, index) => moduleEditor(module, index)).join('')}</div><div class="add-module-menu" id="add-module-menu"><div class="menu-title">选择要添加的模块</div><div class="module-options">${moduleTypes().map(type => `<button data-add-type="${type.type}"><span>${type.icon}</span><b>${type.title}</b><small>${type.hint}</small></button>`).join('')}</div></div>`; }
function modalField(label, path, value, area = false, placeholder = '') { return field(label, path, value, area, placeholder); }
function photoUploadField() { return `<label class="photo-upload-field"><span>头像照片</span><input type="file" accept="image/*" data-photo-input><small>推荐使用清晰的证件照；图片只保存到当前浏览器</small></label>`; }
function profileModal() { return `<div class="modal-shell profile-modal"><div class="modal-head"><div><span class="eyebrow">PROFILE</span><h2>基本信息</h2><p>姓名和联系方式会显示在简历页首</p></div><button class="modal-close" data-modal-close aria-label="关闭">×</button></div><div class="modal-body"><div class="modal-grid">${modalField('姓名', 'profile.name', state.profile.name)}${modalField('求职职位', 'profile.role', state.profile.role)}${modalField('所在城市', 'profile.city', state.profile.city)}${modalField('联系电话', 'profile.phone', state.profile.phone)}${modalField('电子邮箱', 'profile.email', state.profile.email)}${modalField('个人网站', 'profile.website', state.profile.website)}${photoUploadField()}</div></div><div class="modal-foot"><button class="modal-cancel" data-modal-cancel>取消</button><button class="modal-save" data-modal-save>保存修改</button></div></div>`; }
function moduleModal(module) { return `<div class="modal-shell module-modal"><div class="modal-head"><div><span class="eyebrow">MODULE / ${moduleTypeName(module.type).toUpperCase()}</span><h2>${esc(module.title)} <button class="inline-edit" data-edit-title title="编辑模块标题">⌕</button></h2><p>编辑内容后，右侧预览会即时更新</p></div><button class="modal-close" data-modal-close aria-label="关闭">×</button></div><div class="modal-body"><div class="modal-title-field">${modalField('模块标题', `module.${module.id}.title`, module.title)}</div>${moduleFields(module)}<div class="spacing-control modal-spacing"><label>本模块上下留白 <output>${module.spacing}px</output></label><input type="range" min="4" max="64" value="${module.spacing}" data-module-spacing="${module.id}"></div></div><div class="modal-foot"><button class="modal-danger" data-modal-delete="${module.id}">删除模块</button><div><button class="modal-cancel" data-modal-cancel>取消</button><button class="modal-save" data-modal-save>保存修改</button></div></div></div>`; }
function coverModal() { return `<div class="modal-shell settings-modal cover-modal"><div class="modal-head"><div><span class="eyebrow">COVER / HEADER</span><h2>标题与封面</h2><p>调整简历页首的姓名、职位和联系信息</p></div><button class="modal-close" data-modal-close aria-label="关闭">×</button></div><div class="modal-body"><div class="modal-grid">${modalField('姓名', 'profile.name', state.profile.name)}${modalField('求职职位', 'profile.role', state.profile.role)}${modalField('所在城市', 'profile.city', state.profile.city)}${modalField('联系电话', 'profile.phone', state.profile.phone)}${modalField('电子邮箱', 'profile.email', state.profile.email)}${modalField('个人网站', 'profile.website', state.profile.website)}</div></div><div class="modal-foot"><span class="modal-hint">已自动保存</span><button class="modal-save" data-modal-close>完成</button></div></div>`; }
function settingsModal(tool) { const title = tool === 'font' ? '字体与字号' : tool === 'template' ? '选择模板' : '间距与自由布局'; const panel = tool === 'font' ? fontPanel() : tool === 'template' ? templatePanel() : layoutPanel(); const className = tool === 'template' ? 'settings-modal template-settings-modal' : 'settings-modal'; return `<div class="modal-shell ${className}"><div class="modal-head"><div><span class="eyebrow">WORKSPACE SETTINGS</span><h2>${title}</h2><p>设置会自动同步到当前简历</p></div><button class="modal-close" data-modal-close aria-label="关闭">×</button></div><div class="modal-body">${panel}</div><div class="modal-foot"><span class="modal-hint">已自动保存</span><button class="modal-save" data-modal-close>完成</button></div></div>`; }
function addModuleModal() { return `<div class="modal-shell add-module-modal"><div class="modal-head"><div><span class="eyebrow">RESUME MODULES</span><h2>添加简历模块</h2><p>选择一个模块，它会出现在右侧列表和简历画布中</p></div><button class="modal-close" data-modal-close aria-label="关闭">×</button></div><div class="modal-body"><div class="module-options large-module-options">${moduleTypes().map(type => `<button data-add-type="${type.type}"><span>${type.icon}</span><b>${type.title}</b><small>${type.hint}</small></button>`).join('')}</div></div></div>`; }
function renderModal(content, target) { modalTarget = target; if (!modalSnapshot) modalSnapshot = clone(state); const dialogClass = content.includes('template-settings-modal') ? ' template-dialog' : ''; $('#modal-root').innerHTML = `<div class="modal-backdrop" data-modal-backdrop><div class="modal-dialog${dialogClass}" role="dialog" aria-modal="true">${content}</div></div>`; document.body.classList.add('modal-open'); bind(); }
function openProfileModal() { modalSnapshot = clone(state); renderModal(profileModal(), 'profile'); }
function openModuleModal(id) { const module = getModule(id); if (!module) return; modalSnapshot = clone(state); renderModal(moduleModal(module), id); }
function closeSpacingPopover() { const root = $('#workspace-popover'); if (!root) return; root.innerHTML = ''; root.classList.remove('open'); }
function openSpacingPopover(button) { const root = $('#workspace-popover'); if (!root) return; root.innerHTML = `<div class="workspace-popover-panel"><div class="popover-head"><div><span class="eyebrow">LAYOUT</span><b>间距与自由布局</b></div><button data-popover-close aria-label="关闭">×</button></div>${layoutPanel()}</div>`; root.classList.add('open'); const rect = button.getBoundingClientRect(); root.style.left = `${rect.right + 12}px`; root.style.top = `${Math.max(12, rect.top - 6)}px`; bind(); }
function openToolModal(tool) { closeSpacingPopover(); modalSnapshot = clone(state); renderModal(tool === 'cover' ? coverModal() : settingsModal(tool), tool); }
function closeModal(restore = false) { if (restore && modalSnapshot) { state = clone(modalSnapshot); save(); } modalSnapshot = null; modalTarget = null; $('#modal-root').innerHTML = ''; document.body.classList.remove('modal-open'); render(false); renderSidebar(); }
function renderSidebar(tab = document.querySelector('.module-tab.active')?.dataset.moduleTab || 'content') { const node = $('#module-sidebar-content'); if (node) node.innerHTML = moduleSidebar(tab); updateProgress(); bind(); }
function moduleTypes() { return [{ type: 'summary', title: '个人简介', icon: '✦', hint: '一句话介绍你的优势' }, { type: 'experience', title: '工作经历', icon: '↗', hint: '展示工作与成果' }, { type: 'education', title: '教育经历', icon: '⌂', hint: '学校与专业背景' }, { type: 'skills', title: '技能与工具', icon: '◇', hint: '软件、能力、证书' }, { type: 'projects', title: '项目经历', icon: '▤', hint: '重点项目与作品' }, { type: 'awards', title: '奖项与证书', icon: '★', hint: '荣誉与专业认证' }, { type: 'languages', title: '语言能力', icon: '文', hint: '语言和熟练程度' }, { type: 'custom', title: '自定义模块', icon: '＋', hint: '完全自定义内容' }]; }
function moduleEditor(module) { const label = module.visible ? '已显示' : '已隐藏'; return `<article class="module-card ${module.visible ? '' : 'is-hidden'}" data-module="${module.id}"><div class="module-card-head"><div class="drag-grip">⠿</div><div class="module-icon">${moduleIcon(module.type)}</div><div class="module-heading"><strong>${esc(module.title)}</strong><span>${label} · ${moduleTypeName(module.type)}</span></div><div class="module-actions"><button title="显示或隐藏" data-module-action="toggle" data-id="${module.id}">${module.visible ? '◉' : '○'}</button><button title="删除模块" data-module-action="delete" data-id="${module.id}">×</button></div></div><div class="module-card-body">${field('模块标题', `module.${module.id}.title`, module.title)}${moduleFields(module)}<div class="spacing-control"><label>本模块上下留白 <output>${module.spacing}px</output></label><input type="range" min="4" max="64" value="${module.spacing}" data-module-spacing="${module.id}"></div></div></article>`; }
function moduleFields(module) { const prefix = `module.${module.id}`; if (module.type === 'summary' || module.type === 'custom') return field('内容', `${prefix}.content`, module.content, true, '输入模块内容…'); if (module.type === 'skills') return field('技能列表', `${prefix}.skills`, module.skills, true, '用逗号分隔技能'); if (module.type === 'experience') return itemFields(module, ['company', 'role', 'period', 'detail'], ['公司', '职位', '时间', '工作内容与成果']); if (module.type === 'education') return itemFields(module, ['school', 'degree', 'period', 'city'], ['学校', '学历 / 专业', '就读时间', '地点']); if (module.type === 'projects') return itemFields(module, ['name', 'role', 'period', 'detail'], ['项目名称', '角色', '时间', '项目描述']); if (module.type === 'awards') return itemFields(module, ['name', 'issuer', 'period', 'detail'], ['奖项名称', '颁发机构', '时间', '说明']); if (module.type === 'languages') return itemFields(module, ['name', 'level'], ['语言', '熟练程度']); return ''; }
function itemFields(module, keys, labels) { return `<div class="repeatable-fields">${(module.items || []).map((item, index) => `<div class="repeat-item"><div class="repeat-head"><b>${moduleTypeName(module.type)} ${String(index + 1).padStart(2, '0')}</b>${module.items.length > 1 ? `<button data-item-delete="${module.id}" data-item-index="${index}">删除</button>` : ''}</div>${keys.map((key, i) => field(labels[i], `module.${module.id}.items.${index}.${key}`, item[key], key === 'detail')).join('')}</div>`).join('')}<button class="add-repeat" data-item-add="${module.id}">＋ 添加一条</button></div>`; }
function moduleIcon(type) { return ({ summary: '✦', experience: '↗', education: '⌂', skills: '◇', projects: '▤', awards: '★', languages: '文', custom: '＋' })[type] || '＋'; }
function moduleTypeName(type) { return (moduleTypes().find(item => item.type === type) || {}).title || '自定义'; }
function layoutPanel() { const elements = [{ id: 'name', label: '姓名' }, { id: 'role', label: '职位' }, { id: 'contact', label: '联系方式' }, { id: 'header', label: '表头整体' }]; return `<div class="settings-panel"><div class="settings-title">布局设置<span>控制整份简历的空间关系</span></div><div class="setting-grid">${rangeSetting('纸张左右边距', 'pagePadding', state.settings.pagePadding, 28, 90, 'px')}${rangeSetting('模块间距基准', 'moduleGap', state.settings.moduleGap, 4, 60, 'px')}${rangeSetting('行高', 'lineHeight', state.settings.lineHeight, 1.25, 2.1, '')}</div><div class="setting-block"><label>分栏方式</label><div class="segmented">${['single', 'split'].map(value => `<button class="${(state.settings.columns || 'single') === value ? 'active' : ''}" data-setting="columns" data-value="${value}">${value === 'single' ? '单栏' : '左右分栏'}</button>`).join('')}</div></div><div class="setting-block"><label>标题分隔线</label><div class="segmented">${['line', 'dot', 'none'].map(value => `<button class="${state.settings.sectionRule === value ? 'active' : ''}" data-setting="sectionRule" data-value="${value}">${value === 'line' ? '细线' : value === 'dot' ? '短线' : '无'}</button>`).join('')}</div></div><div class="setting-block element-layout-block"><label>单个元素自由布局 <small>也可以直接点击右侧预览中的姓名、职位或联系方式</small></label><div class="segmented element-tabs">${elements.map(item => `<button class="${selectedElement === item.id ? 'active' : ''}" data-element-select="${item.id}">${item.label}</button>`).join('')}</div><div class="setting-grid element-setting-grid">${elementRangeSetting(selectedElement, 'fontSize', '字号', state.settings.elementStyles[selectedElement]?.fontSize ?? 14, 10, 64, 'px')}${elementRangeSetting(selectedElement, 'x', '左右位置', state.settings.elementStyles[selectedElement]?.x ?? 0, -80, 80, 'px')}${elementRangeSetting(selectedElement, 'y', '上下位置', state.settings.elementStyles[selectedElement]?.y ?? 0, -80, 80, 'px')}${elementRangeSetting(selectedElement, 'marginBottom', '下方间距', state.settings.elementStyles[selectedElement]?.marginBottom ?? 0, 0, 80, 'px')}</div></div></div>`; }
function templateDefinitions() { return [{ id: 'left-right', name: '推荐 · 图标横排', note: '照片、图标信息与三列经历' }, { id: 'classic', name: '经典留白', note: '稳重清晰' }, { id: 'modern', name: '现代强调', note: '蓝色侧栏与色块' }, { id: 'minimal', name: '极简黑白', note: '细线与留白' }, { id: 'editorial', name: '编辑风格', note: '杂志式大标题' }, { id: 'mono', name: '单色商务', note: '高密度信息' }, { id: 'soft', name: '柔和圆角', note: '圆角与柔和色彩' }]; }
function templatePanel() { const templates = templateDefinitions(); return `<div class="settings-panel"><div class="settings-title">模板库<span>点击缩略图即可实时切换，模板结构和视觉层级会同步变化</span></div><div class="template-gallery">${templates.map(item => `<button class="template-card ${state.settings.template === item.id ? 'active' : ''}" data-setting="template" data-value="${item.id}"><span class="template-thumb ${item.id}"><i></i><i></i><i></i></span><b>${item.name}</b><small>${item.note}</small></button>`).join('')}</div><div class="setting-block"><label>主题色</label><div class="color-row">${['#2e7b6f', '#2c5e8f', '#9b5b43', '#343b44', '#855d8d', '#b87936'].map(color => `<button class="color-swatch ${state.settings.accent === color ? 'active' : ''}" style="--swatch:${color}" data-setting="accent" data-value="${color}"></button>`).join('')}<label class="custom-color"><input type="color" value="${state.settings.accent}" data-setting-input="accent">自定义</label></div></div><div class="setting-grid">${rangeSetting('纸张圆角', 'paperRadius', state.settings.paperRadius, 0, 18, 'px')}</div></div>`; }
function fontPanel() { return `<div class="settings-panel font-settings-panel"><div class="settings-title">字体设置<span>字体类型和正文大小会即时作用于整份简历</span></div><div class="setting-grid">${selectSetting('字体类型', 'font', state.settings.font, [{ value: 'system', label: '系统无衬线' }, { value: 'serif', label: '人文衬线' }, { value: 'mono', label: '等宽字体' }])}${rangeSetting('正文大小', 'fontSize', state.settings.fontSize, 10, 22, 'px')}</div><div class="font-preview">Aa　林知行　产品设计师<br><small>拖动字号滑块，右侧预览会实时更新</small></div></div>`; }
function elementRangeSetting(id, key, label, value, min, max, unit) { return `<label class="range-setting"><span>${label}<output>${value}${unit}</output></span><input type="range" min="${min}" max="${max}" value="${value}" data-element-setting="${id}.${key}" data-element-unit="${unit}"></label>`; }
function rangeSetting(label, key, value, min, max, unit) { return `<label class="range-setting"><span>${label}<output>${value}${unit}</output></span><input type="range" min="${min}" max="${max}" step="${key === 'lineHeight' ? '.05' : '1'}" value="${value}" data-setting-input="${key}"></label>`; }
function selectSetting(label, key, value, options) { return `<label class="select-setting"><span>${label}</span><select data-setting-input="${key}">${options.map(option => `<option value="${option.value}" ${option.value === value ? 'selected' : ''}>${option.label}</option>`).join('')}</select></label>`; }

function elementStyle(id, includeFont = false) { const style = state.settings.elementStyles?.[id] || {}; const rules = [`position:relative`, `left:${Number(style.x || 0)}px`, `top:${Number(style.y || 0)}px`]; if (includeFont && style.fontSize) rules.push(`font-size:${Number(style.fontSize)}px`); if (style.marginBottom != null) rules.push(`margin-bottom:${Number(style.marginBottom)}px`); return `style="${rules.join(';')}"`; }
function contactItems(profile) { return [{ icon: '▣', value: profile.employmentStatus || profile.status }, { icon: '▣', value: profile.birthDate }, { icon: '✉', value: profile.email }, { icon: '⌕', value: profile.phone }, { icon: '⌖', value: profile.city }, { icon: '◎', value: profile.website }].filter(item => item.value); }
function resume() { const p = state.profile; const leftRight = state.settings.template === 'left-right'; const photo = p.photo ? `<img src="${esc(p.photo)}" alt="${esc(p.name)}" class="resume-photo-image">` : `<span class="resume-photo-initial">${esc(String(p.name || 'R').slice(0, 1))}</span>`; const contacts = leftRight ? contactItems(p).map(item => `<span class="contact-item"><i>${item.icon}</i><span>${esc(item.value)}</span></span>`).join('') : [p.city, p.phone, p.email, p.website].filter(Boolean).map(value => `<span>${esc(value)}</span>`).join(''); return `<header class="resume-head ${leftRight ? 'left-right-head' : ''}" data-element-id="header" ${elementStyle('header')}>${leftRight ? `<div class="resume-profile-photo">${photo}</div>` : ''}<div class="resume-identity"><div class="resume-name" data-element-id="name" ${elementStyle('name', true)}>${esc(p.name)}</div><div class="resume-role" data-element-id="role" ${elementStyle('role', true)}>${esc(p.role)}</div></div><div class="contact-line ${leftRight ? 'left-right-contact' : ''}" data-element-id="contact" ${elementStyle('contact', true)}>${contacts}</div></header><div class="resume-columns ${state.settings.columns === 'split' ? 'split' : ''}"><div class="resume-main">${activeModules().map(renderModule).join('')}</div></div>`; }
function renderSkillList(value) { const items = String(value || '').split(/[,，\\n]+/).map(item => item.trim()).filter(Boolean); return items.map(item => `<span class="skill-bullet">${esc(item)}</span>`).join(''); }
function renderModule(module) { const style = `style="--module-space:${module.spacing}px"`; const leftRight = state.settings.template === 'left-right'; let body = ''; if (module.type === 'summary' || module.type === 'custom') body = `<p class="summary">${esc(module.content)}</p>`; if (module.type === 'skills') body = leftRight ? `<div class="skill-list">${renderSkillList(module.skills)}</div>` : `<p class="skill-line">${esc(module.skills)}</p>`; if (module.type === 'experience') body = (module.items || []).map(item => leftRight ? `<div class="exp-item"><div class="exp-row left-right-item-row"><strong>${esc(item.role)}</strong><span class="exp-company">${esc(item.company)}</span><span class="exp-date">${esc(item.period)}</span></div><p class="exp-detail">${esc(item.detail)}</p></div>` : `<div class="exp-item"><div class="exp-row"><strong>${esc(item.role)}</strong><span class="exp-date">${esc(item.period)}</span></div><div class="exp-company">${esc(item.company)}</div><p class="exp-detail">${esc(item.detail)}</p></div>`).join(''); if (module.type === 'education') body = (module.items || []).map(item => `<div class="edu-row"><div class="edu-main"><strong>${esc(item.school)}</strong><p>${esc(item.degree)} · ${esc(item.city)}</p></div><span class="exp-date">${esc(item.period)}</span></div>`).join(''); if (module.type === 'projects') body = (module.items || []).map(item => leftRight ? `<div class="project-item"><div class="exp-row left-right-item-row"><strong>${esc(item.name)}</strong><span class="exp-company">${esc(item.role)}</span><span class="exp-date">${esc(item.period)}</span></div><p class="exp-detail">${esc(item.detail)}</p></div>` : `<div class="project-item"><div class="exp-row"><strong>${esc(item.name)}</strong><span class="exp-date">${esc(item.period)}</span></div><div class="exp-company">${esc(item.role)}</div><p class="exp-detail">${esc(item.detail)}</p></div>`).join(''); if (module.type === 'awards') body = (module.items || []).map(item => `<div class="edu-row"><div class="edu-main"><strong>${esc(item.name)}</strong><p>${esc(item.issuer)} · ${esc(item.detail)}</p></div><span class="exp-date">${esc(item.period)}</span></div>`).join(''); if (module.type === 'languages') body = `<div class="language-list">${(module.items || []).map(item => `<span><b>${esc(item.name)}</b>${esc(item.level)}</span>`).join('')}</div>`; return `<section class="resume-section type-${module.type}" ${style}><h3>${esc(module.title)}</h3>${body}</section>`; }
function bindPreviewSelection() { $$('[data-element-id]').forEach(element => { element.onclick = event => { event.preventDefault(); event.stopPropagation(); selectedElement = element.dataset.elementId; $$('.paper [data-element-id]').forEach(item => item.classList.toggle('is-selected', item === element)); toast(`已选中${({ name: '姓名', role: '职位', contact: '联系方式', header: '表头整体' })[selectedElement] || '元素'}，可在“间距”中调整`); }; }); }
function render(rebuild = true) { if (rebuild) { $('#app').innerHTML = shell(); bind(); } else { const paper = $('#paper'); if (paper) { paper.className = `paper ${state.settings.template}`; paper.innerHTML = resume(); bindPreviewSelection(); } } applyVisualSettings(); updateProgress(); }
function applyVisualSettings() { const fontMap = { system: 'Inter, "SF Pro Display", "Noto Sans SC", "Microsoft YaHei", Arial, sans-serif', serif: 'Georgia, "Songti SC", "SimSun", serif', mono: '"SFMono-Regular", Consolas, "Liberation Mono", monospace' }; document.documentElement.style.setProperty('--accent', state.settings.accent); document.documentElement.style.setProperty('--page-padding', `${state.settings.pagePadding}px`); document.documentElement.style.setProperty('--font-size', `${state.settings.fontSize}px`); document.documentElement.style.setProperty('--line-height', state.settings.lineHeight); document.documentElement.style.setProperty('--paper-radius', `${state.settings.paperRadius}px`); document.documentElement.style.setProperty('--module-gap', `${state.settings.moduleGap}px`); document.documentElement.style.setProperty('--resume-font', fontMap[state.settings.font] || fontMap.system); const paper = $('#paper'); if (paper) { paper.dataset.rule = state.settings.sectionRule; paper.style.transform = `scale(${previewZoom / 100})`; paper.style.marginBottom = `${(1 - previewZoom / 100) * -1123}px`; $('#ztext').textContent = `${previewZoom}%`; } }
function updateProgress() { const count = [state.profile.name, state.profile.role, ...activeModules().map(module => module.type === 'summary' ? module.content : module.type === 'skills' ? module.skills : module.items?.length ? 'yes' : '')].filter(Boolean).length; const progress = $('#progress'); if (progress) progress.textContent = `${Math.min(100, Math.round(count / (state.modules.length + 2) * 100))}%`; }
function setPath(path, value) { const parts = path.split('.'); if (parts[0] === 'module') { const module = getModule(parts[1]); if (!module) return; let target = module; parts.slice(2, -1).forEach(key => { target = target[key]; }); target[parts.at(-1)] = value; } else { let target = state; parts.slice(0, -1).forEach(key => { target = target[key]; }); target[parts.at(-1)] = value; } save(); }
function syncRange(input) { const min = Number(input.min || 0); const max = Number(input.max || 100); const value = Number(input.value); const progress = max === min ? 0 : Math.max(0, Math.min(100, ((value - min) / (max - min)) * 100)); input.style.setProperty('--range-progress', `${progress}%`); }
function bind() {
  $$('[data-path]').forEach(input => input.oninput = () => { setPath(input.dataset.path, input.value); render(false); });
  $$('[data-photo-input]').forEach(input => input.onchange = () => { const file = input.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { state.profile.photo = String(reader.result || ''); save(); render(false); toast('头像已更新'); }; reader.readAsDataURL(file); });
  $$('[data-module-spacing]').forEach(input => { syncRange(input); input.oninput = () => { const module = getModule(input.dataset.moduleSpacing); if (!module) return; module.spacing = +input.value; syncRange(input); const output = input.closest('.spacing-control')?.querySelector('output'); if (output) output.textContent = `${input.value}px`; save(); render(false); }; });
  $$('[data-action]').forEach(button => button.onclick = event => { event.stopPropagation(); actions(button.dataset.action); });
  $$('[data-tool]').forEach(button => button.onclick = event => { event.stopPropagation(); $$('.tool-button').forEach(item => item.classList.toggle('active', item === button)); if (button.dataset.tool === 'spacing') openSpacingPopover(button); else openToolModal(button.dataset.tool); });
  $$('[data-popover-close]').forEach(button => button.onclick = event => { event.stopPropagation(); closeSpacingPopover(); });
  $$('[data-open-profile]').forEach(button => button.onclick = () => openProfileModal());
  $$('[data-open-module]').forEach(button => button.onclick = () => openModuleModal(button.dataset.openModule));
  $$('[data-module-toggle]').forEach(button => button.onclick = event => { event.stopPropagation(); const module = getModule(button.dataset.moduleToggle); if (!module) return; module.visible = !module.visible; save(); render(false); renderSidebar(); toast(module.visible ? '模块已显示' : '模块已隐藏'); });
  $$('[data-module-action]').forEach(button => button.onclick = event => { event.stopPropagation(); moduleAction(button.dataset.moduleAction, button.dataset.id); });
  $$('[data-sort-id]').forEach(row => {
    row.ondragstart = event => {
      event.dataTransfer.effectAllowed = 'move';
      event.dataTransfer.setData('text/plain', row.dataset.sortId);
      row.classList.add('is-dragging');
    };
    row.ondragend = () => {
      row.classList.remove('is-dragging');
      $$('.sort-row').forEach(item => item.classList.remove('drag-over'));
    };
    row.ondragover = event => {
      event.preventDefault();
      event.dataTransfer.dropEffect = 'move';
      row.classList.add('drag-over');
    };
    row.ondragleave = () => row.classList.remove('drag-over');
    row.ondrop = event => {
      event.preventDefault();
      row.classList.remove('drag-over');
      const sourceId = event.dataTransfer.getData('text/plain');
      const targetId = row.dataset.sortId;
      if (!sourceId || sourceId === targetId) return;
      const sourceIndex = state.modules.findIndex(module => module.id === sourceId);
      const targetIndex = state.modules.findIndex(module => module.id === targetId);
      if (sourceIndex < 0 || targetIndex < 0) return;
      const [moved] = state.modules.splice(sourceIndex, 1);
      state.modules.splice(targetIndex, 0, moved);
      save();
      render(false);
      renderSidebar('sort');
      toast('模块顺序已更新');
    };
  });
  $$('[data-item-delete]').forEach(button => button.onclick = event => { event.stopPropagation(); const module = getModule(button.dataset.itemDelete); if (!module) return; module.items.splice(+button.dataset.itemIndex, 1); save(); if (modalTarget === module.id) renderModal(moduleModal(module), module.id); else render(); });
  $$('[data-item-add]').forEach(button => button.onclick = event => { event.stopPropagation(); const module = getModule(button.dataset.itemAdd); if (!module) return; module.items.push(emptyItem(module.type)); save(); if (modalTarget === module.id) renderModal(moduleModal(module), module.id); else render(); });
  $$('[data-module-tab]').forEach(button => button.onclick = () => { $$('.module-tab').forEach(item => item.classList.toggle('active', item === button)); renderSidebar(button.dataset.moduleTab); });
  $$('[data-setting]').forEach(button => button.onclick = () => { const key = button.dataset.setting; state.settings[key] = button.dataset.value; save(); render(false); if (modalTarget) renderModal(settingsModal(modalTarget), modalTarget); else $$(`[data-setting="${key}"]`).forEach(item => item.classList.toggle('active', item === button)); });
  $$('[data-setting-input]').forEach(input => { syncRange(input); const updateSettingInput = () => { const key = input.dataset.settingInput; const value = input.type === 'range' ? +input.value : input.value; if (key === 'moduleGap' && value !== state.settings.moduleGap) { state.modules.forEach(module => { if (module.spacing === state.settings.moduleGap) module.spacing = value; }); } state.settings[key] = value; syncRange(input); save(); const output = input.closest('label')?.querySelector('output'); if (output && input.type === 'range') output.textContent = `${input.value}${key === 'lineHeight' ? '' : 'px'}`; render(false); }; input.oninput = updateSettingInput; input.onchange = updateSettingInput; });
  $$('[data-element-select]').forEach(button => button.onclick = event => { event.stopPropagation(); selectedElement = button.dataset.elementSelect; if (modalTarget) renderModal(settingsModal(modalTarget), modalTarget); else { closeSpacingPopover(); const spacingButton = document.querySelector('[data-tool="spacing"]'); if (spacingButton) openSpacingPopover(spacingButton); } });
  $$('[data-element-setting]').forEach(input => { syncRange(input); input.oninput = () => { const [id, key] = input.dataset.elementSetting.split('.'); state.settings.elementStyles[id] = { ...(state.settings.elementStyles[id] || {}), [key]: +input.value }; syncRange(input); const output = input.closest('label')?.querySelector('output'); if (output) output.textContent = `${input.value}${input.dataset.elementUnit || ''}`; save(); render(false); if (modalTarget) renderModal(settingsModal(modalTarget), modalTarget); }; });
  $$('[data-add-type]').forEach(button => button.onclick = () => { addModule(button.dataset.addType); closeModal(); });
  $$('[data-modal-close], [data-modal-cancel]').forEach(button => button.onclick = () => closeModal(button.hasAttribute('data-modal-cancel')));
  $$('[data-modal-save]').forEach(button => button.onclick = () => { save(); closeModal(); toast('修改已保存'); });
  $$('[data-modal-delete]').forEach(button => button.onclick = () => { moduleAction('delete', button.dataset.modalDelete); closeModal(); });
  $$('[data-modal-backdrop]').forEach(backdrop => { let pressedOnBackdrop = false; backdrop.onpointerdown = event => { pressedOnBackdrop = event.target === backdrop; }; backdrop.onclick = event => { if (event.target === backdrop && pressedOnBackdrop) closeModal(true); pressedOnBackdrop = false; }; });
  $$('[data-edit-title]').forEach(button => button.onclick = () => document.querySelector('.modal-title-field input')?.focus());
  if (!window.__workspacePopoverBound) { document.addEventListener('click', event => { const root = $('#workspace-popover'); if (root?.classList.contains('open') && !event.target.closest('#workspace-popover') && !event.target.closest('[data-tool="spacing"]')) closeSpacingPopover(); }); window.__workspacePopoverBound = true; }
  bindPreviewSelection();
}
function actions(action) { if (action === 'add-module') { modalSnapshot = clone(state); renderModal(addModuleModal(), 'add-module'); return; } if (action === 'zoom-in') { previewZoom = Math.min(125, previewZoom + 5); applyVisualSettings(); } if (action === 'zoom-out') { previewZoom = Math.max(55, previewZoom - 5); applyVisualSettings(); } if (action === 'preview') togglePreview(); if (action === 'pdf') exportPdf(); if (action === 'image') exportImage(); if (action === 'share') { navigator.clipboard?.writeText(location.href); toast('链接已复制'); } }
function moduleAction(action, id) { const index = state.modules.findIndex(module => module.id === id); if (index < 0) return; const activeTab = document.querySelector('.module-tab.active')?.dataset.moduleTab || 'content'; if (action === 'toggle') state.modules[index].visible = !state.modules[index].visible; if (action === 'delete') { state.modules.splice(index, 1); toast('模块已删除'); } if (action === 'up' && index > 0) [state.modules[index - 1], state.modules[index]] = [state.modules[index], state.modules[index - 1]]; if (action === 'down' && index < state.modules.length - 1) [state.modules[index + 1], state.modules[index]] = [state.modules[index], state.modules[index + 1]]; save(); render(); if (activeTab === 'sort') renderSidebar('sort'); }
function addModule(type) { const module = { id: uid(type), type, title: moduleTypeName(type), visible: true, spacing: 22, content: '', skills: '', items: [] }; if (type === 'summary' || type === 'custom') module.content = type === 'custom' ? '在这里写下你的补充信息。' : '在这里写下你的个人简介。'; if (type === 'skills') module.skills = '技能一, 技能二, 技能三'; if (['experience', 'education', 'projects', 'awards', 'languages'].includes(type)) module.items.push(emptyItem(type)); state.modules.push(module); save(); render(); toast('模块已添加'); }
function emptyItem(type) { return ({ experience: { company: '公司名称', role: '职位名称', period: '2022.01 — 至今', detail: '描述你的工作内容与成果。' }, education: { school: '学校名称', degree: '专业 · 学历', period: '2018.09 — 2022.06', city: '城市' }, projects: { name: '项目名称', role: '项目角色', period: '2024', detail: '描述项目背景、你的贡献和结果。' }, awards: { name: '奖项或证书', issuer: '颁发机构', period: '2024', detail: '补充说明' }, languages: { name: '语言', level: '熟练程度' } })[type] || {}; }
function togglePreview(requestFullscreen = true) { const active = document.body.classList.toggle('preview-mode'); const button = $('#full'); const topButton = $('#top-preview'); if (button) button.textContent = active ? '× 退出预览' : '⛶ 专注预览'; if (topButton) topButton.textContent = active ? '× 退出预览' : '⛶ 预览'; if (active && requestFullscreen) document.documentElement.requestFullscreen?.().catch(() => {}); if (!active && document.fullscreenElement) document.exitFullscreen?.(); toast(active ? '已进入预览模式' : '已退出预览模式'); }
function safeFilename(value) { return String(value || '我的简历').replace(/[\\/:*?"<>|]/g, '').trim() || '我的简历'; }
async function captureResumeCanvas() { const paper = $('#paper'); if (!paper) throw new Error('找不到简历预览'); const clone = paper.cloneNode(true); clone.style.setProperty('transform', 'none', 'important'); clone.style.setProperty('margin', '0', 'important'); clone.style.setProperty('box-shadow', 'none', 'important'); clone.style.width = '794px'; clone.style.minHeight = '1123px'; clone.style.position = 'fixed'; clone.style.left = '-10000px'; clone.style.top = '0'; clone.style.zIndex = '-1'; document.body.appendChild(clone); try { await document.fonts?.ready; return await html2canvas(clone, { backgroundColor: '#fff', scale: 2, useCORS: true, logging: false, width: 794, height: 1123, windowWidth: 794 }); } finally { clone.remove(); } }
function downloadBlob(blob, filename) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.download = filename; link.href = url; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
async function exportImage() { try { toast('正在生成图片'); const canvas = await captureResumeCanvas(); const blob = await new Promise((resolve, reject) => canvas.toBlob(result => result ? resolve(result) : reject(new Error('图片生成失败')), 'image/png')); downloadBlob(blob, `简历-${safeFilename(state.profile.name)}.png`); toast('图片已下载'); } catch (error) { console.error(error); toast('图片导出失败，请重试'); } }
async function exportPdf() { try { toast('正在生成 PDF'); const canvas = await captureResumeCanvas(); const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4', compress: true }); pdf.addImage(canvas.toDataURL('image/jpeg', 0.94), 'JPEG', 0, 0, 210, 297, undefined, 'FAST'); pdf.save(`简历-${safeFilename(state.profile.name)}.pdf`); toast('PDF 已下载'); } catch (error) { console.error(error); toast('PDF 导出失败，请重试'); } }
document.addEventListener('fullscreenchange', () => { if (!document.fullscreenElement && document.body.classList.contains('preview-mode')) togglePreview(false); });
document.addEventListener('keydown', event => { if (event.key === 'Escape' && document.body.classList.contains('modal-open')) closeModal(true); });
render();
